version: "3.9"

services:
    db:
        image: bitnami/postgresql
        ports:
            - "${DB_PORT}:5432"
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}

#    server:
#        build: .
#        command: uvicorn app.main:app --host 0.0.0.0
#        volumes:
#            - .:/app
#        ports:
#            - 8008:8000
#        depends_on:
#            - postgres